### PR TITLE
Test - Validate Models #8

### PR DESCRIPTION
**Pull request by EnmaGalindo**
…con #8

### CODE REVIEW

**Comment by VictorD-Bohorquez** [comment]
Hi @EnmaGalindo , I see some issues in the additions:

- Please avoid adding scripts at the __init__.py file, as you may know , this is the launching file for the modules (folders), hence, that script / file, may interrupt / create conflic with the other users files, as everyone is working on the same directory. Please change the file name to avoid this conflicts.
- The general script is great, yet, there are no tests conducted, testing involves making assertions over the things you are testing (Comparing code return values against the expected ones), that's completly missing. Pleasea add assertions to the script, here you can find documentation on how to do so: https://docs.pytest.org/en/stable/

**Review by VictorD-Bohorquez — CHANGES_REQUESTED** [review]
Hi @EnmaGalindo Please change the following:

- Change the init file name to avoid affecting the other people that is working on the same directory,
- Add test assertions to be able to consider the script a test.

I added a comment in the main PR conversation, with further instructions .

**Comment by VictorD-Bohorquez** [comment]
@EnmaGalindo By the way, please follow up the code standards, in the test_model_performance file, a main method is requiered. Please also follow the commit format we stablished: "Add your message -Initials".

**Comment by VictorD-Bohorquez** [comment]
@EnmaGalindo Additionaly please avoid creating branches for every change or feature you work on, the main purpose of each member to have a personal branch is to work and upload changes from that branch. In case you need to work on different branches, please follow up the naming convention we stablished since the start of the project:  "MLOps-NameLastname".

**Comment by EnmaGalindo** [comment]
Changes were made in the PR created by MLOps_RubenGuerrero.

**Pull request closed without merging**
